### PR TITLE
Features and Bug Fixes

### LINKED ISSUE #76: store market to appsettings.config to be configurable.

### PR DESCRIPTION
**Pull request by ProIcons**
Fixed #76, #73, #70
Implemented #75, #74, #72, #71, #69

### CODE REVIEW

**Comment by ProIcons** [comment]
At this point i want to note that storing these access tokens unencrypted is not a good idea. There needs to be some kind of data protection which i'm working on it.

**Comment by ProIcons** [comment]
I implemented security on https://github.com/Jessicaward/SpotNetCore/pull/68/commits/301cabccc7a74d6bb0f843f7fbd4f41fb1566dd8

**Comment by srth21** [comment]
> At this point i want to note that storing these access tokens unencrypted is not a good idea. There needs to be some kind of data protection which i'm working on it.

How about some form of a local cache?

**Comment by ProIcons** [comment]
Since the project isn't using appsettings.json for actuall app settings, i stored it inside there , encrypted. refer to the last commit.

**Pull request closed without merging**
